### ISSUE TITLE
Elementary Theme 0.4

### ISSUE THREAD

**Issue by piotrkubisa** [piotrkubisa/sublime-elementary#1]
## General
- [x] Merge [piqus/elementary](https://github.com/piqus/elementary) into [piqus/sublime-elementary](https://github.com/piqus/sublime-elementary)
- [x] Add it to wbond/package_control_channel#4387 
- [x] Add note about project roots (It is fork from [samuelrafo/elementary](https://github.com/samuelrafo/elementary) and ~~of course soda-theme~~ Default theme)
- [X] ~~Add sidebar icons for each file type (with switchable settings entry).~~ Please, use [A File Icon](https://github.com/ihodev/a-file-icon) package instead.
- [x] Merge themes from [piqus/sublime-themes](https://github.com/piqus/sublime-themes)?
- [x] Adapt icons from elementary icons.
- [x] Add content to gh-pages
- [x] Add screenshots to README.md (depends on `gh-pages`, because that branch should have screenshots/ directory)
## Dark Variant
- [x] Adapt dark theme from scratch (and of course from Scratch-text-editor) instead of copying piqus/elementary.
- [x] Modify current tab-list look and feel to be more elementarized.
- [x] FIx non-bold folder label
- [x] Fix theme custom settings.
## Light Variant
- [x] Fix sidebar folder icon hover.
- [x] Add sidebar folder icons.

**Comment by piqus** [comment]
Sprint 1:
![2015-04-30_235400](https://cloud.githubusercontent.com/assets/3073499/7423312/55598610-ef94-11e4-9f77-f46723f9e286.png)

I don't really like tabs, they are only for eagle-eyed dudes.

**Comment by piqus** [comment]
Sprint 2:

![2015-05-01_201815](https://cloud.githubusercontent.com/assets/3073499/7434971/71d4b6ce-f03f-11e4-9efb-6b1f26d7d288.png)

Oh, you can always back to normal dark scrollbars by setting `elementary_colorful: false`: 

![2015-05-01_201911](https://cloud.githubusercontent.com/assets/3073499/7434974/7a08c362-f03f-11e4-8661-c5ae083b7f4e.png)

Added scrollbars (overlay), button skins, find switches and of course I attached a colour scheme which seems to be better than lovely Solarized.

**Comment by piqus** [comment]
Sprint 3:

I pushed first commit with content of theme (many wows). What I did? I styled autocomplete, quickpanel and added pull request to package control. Results you can see below on screenshots:

![2015-05-02_132702](https://cloud.githubusercontent.com/assets/3073499/7440900/f98cbd52-f0ce-11e4-8d9d-a04e76aa3dcd.png)

![2015-05-02_131430](https://cloud.githubusercontent.com/assets/3073499/7440907/1b351a80-f0cf-11e4-8575-69cab88d300b.png)

I heard you like configurations, right? So I put next two: `elementary_dark_statusbar` and `elementary_light_bottombar` to give you make such dark badass searchbar:

![2015-05-02_132108](https://cloud.githubusercontent.com/assets/3073499/7440902/03168e34-f0cf-11e4-9f59-d055be7883d5.png)

Or brighten:

![2015-05-02_131919](https://cloud.githubusercontent.com/assets/3073499/7440903/0d9a2f64-f0cf-11e4-91e4-07c4379ec024.png)

Real-quick indeed.

**Comment by piqus** [comment]
Sprint 4:
I merged my fork [piqus/elementary](https://github.com/piqus/elementary) of fabulous [samuelrafo/elementary](https://github.com/samuelrafo/elementary). Additionally added hover state on sidebar folder icons.

**Comment by piqus** [comment]
Sprint 5:

I have added some information about theme in README.md. I need to add some screenshots there, but first I need to update `gh-pages` branch.

**Comment by piqus** [comment]
Sprint 6:

I created website using awsome `github-pages` feature, and started adding content to http://piqus.github.io/sublime-elementary/ and README.md.

**Comment by piqus** [comment]
Sprint 7:

I fixed some *bugs* (inconsistent design) like white panel during Project Quick Switch (Ctrl+Alt+P) using Dark Variant.

There are free.more changes:

![2015-05-15_232834](https://cloud.githubusercontent.com/assets/3073499/7662285/e38831da-fb5a-11e4-978f-cd1d9b5628d5.png)

* I added some symbolic icons from well-known elementary icons (there are also 4? icons designed espectially for this theme by me :stuck_out_tongue_closed_eyes: ). 
* Search config buttons are tinted not displayed on other background.
* Scrollbars in sidebar are grey not blue, so they are not so disturbing during coding anymore. Of course if you are using`"elementary_colorful": true`.

**Comment by piqus** [comment]
I am going to roll up some new updates compatible with the newest sublime3-dev builds and elementary styles:

- improved tabs UI (overlapping is way prettier) and UX (active, hovered. normal are easier recognizable),
- toggle buttons on searchbar tries to apply style known from Spotify client or from Scratch Editor where some buttons on header bar are circle shaped and highlighted when active.
- the v0.3 has white separators on statusbar. I claim it is a unexpected regression,

**Comment by piotrkubisa** [comment]
I am closing this issue, because with the newest version [3dev](https://www.sublimetext.com/3dev) release (3133) Sublime Team has introduced the Default and Default Adaptive themes which personally, they matches my needs (with some configuration and packages). 

Frankly, I am not going to introduce any changes in future, because I don't like their current UI elements, so I lost the interest in mimicking them. If you are interested with maintenance and/or transferring ownership of `Theme - Elementary` to you. If yes, then please copy this repository and then create a PR to change link in Package Control manager repository.
